### ISSUE TITLE
Duplicate Api scopes found AB#43

### ISSUE THREAD

**Issue by carlospence** [albertodall/IdentityServer4.NHibernate#1]
There is a bug in the ResourceStore.cs file that leads to that error caused by how the method GetAllResourcesAsync() was implemented. This error is always thrown whenever an ApiResource has more than 1 apiscope because IdentityServer4 now checks for Duplicate apiscope names.

I battled with the error for sometime before realizing that it is from the Nhibernate implementation of ResourceStore. I had to check the EntityFramework version since yours is also a port of it.

I rewrote the method using Query instead of QueryOver and it worked perfectly.

        /// <summary>
        /// Gets all resources.
        /// </summary>
        public async Task<Resources> GetAllResourcesAsync()
        {
            Resources result = null;
            using (var tx = _session.BeginTransaction())
            {
                //var identityResources = _session.QueryOver<Entities.IdentityResource>()
                //    .Fetch(SelectMode.Fetch, ir => ir.UserClaims)
                //    .Fetch(SelectMode.Fetch, ir => ir.Properties)
                //    .Future();
                var identityResources = _session.Query<Entities.IdentityResource>()
                    .FetchMany(x => x.UserClaims)
                    .FetchMany(x => x.Properties)
                    .ToFuture();

                //var apiResources = _session.QueryOver<Entities.ApiResource>()
                //    .Fetch(SelectMode.Fetch, ar => ar.Secrets)
                //    .Fetch(SelectMode.Fetch, ar => ar.Scopes)
                //    .Fetch(SelectMode.Fetch, ar => ar.UserClaims)
                //    .Fetch(SelectMode.Fetch, ar => ar.Properties)
                //    .Future();

                var apiResources = _session.Query<Entities.ApiResource>()
                    .FetchMany(x => x.Secrets)
                    .FetchMany(x => x.Scopes).ThenFetchMany(x => x.UserClaims)
                    .FetchMany(x => x.UserClaims)
                    .FetchMany(x => x.Properties).ToFuture();

                result = new Resources(
                    (await identityResources.GetEnumerableAsync())
                        .Select(identity => _mapper.Map<IdentityServer4.Models.IdentityResource>(identity))
                        .ToArray(),
                    (await apiResources.GetEnumerableAsync())
                        .Select(api => _mapper.Map<IdentityServer4.Models.ApiResource>(api))
                        .ToArray()
                );

                await tx.CommitAsync();
            }

            _logger.LogDebug("Found {scopes} as all scopes in database", 
                result.IdentityResources.Select(identity => identity.Name)
                    .Union(result.ApiResources.SelectMany(api => api.Scopes)
                .Select(scope => scope.Name)));

            return await Task.FromResult(result);
        }

**Comment by albertodall** [comment]
Hi @carlospence,
Thanks for reporting this issue, and, more important, for fixing it!
If you want, you can open a pull request, so we can review your code together, and include it.
It would also be great if you could add a test that reproduces the issue.
What do you think?

**Comment by carlospence** [comment]
Ok no problem, will work on that over the weekend.

**Comment by albertodall** [comment]
@carlospence I bumped into the same problem, and I needed to fix it quickly.
I opened my own pull request, and I'm going to release the fix ASAP.
