### ISSUE TITLE
Session is closed exception - AB#57

### ISSUE THREAD

**Issue by lcetinapta** [albertodall/IdentityServer4.NHibernate#11]
Hi,
I have found another issue.
The issue happens when using Client CORS. it happens because of this line of code in CorsPolicyService.cs:
` using (var session = _context.HttpContext.RequestServices.GetRequiredService<IStatelessSession>())`

Here You are explicitly disposing session, and this leads to closing the connection on the database. So next time I request an IStatelessSession instance I will get a closed one.
Because You are registering IStatelessSession in the DI container as Scoped, You don't need to manage it's lifetime yourserf. It will be managed by the DI container.
I would replace this line with this:

`using(var transaction = _session.BeginTransaction()){
...
transaction.RollBack();
}`

And would include IStatelessSession as parameter in the constructor of the class: CorsPlicyService like this...
` public CorsPolicyService(IHttpContextAccessor context, ILogger<CorsPolicyService> logger, IStatelessSession session)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _logger = logger;
            _session = session;
        }`

**Comment by albertodall** [comment]
Hi @lcetinapta 
Thanks for reporting the issue.
Could you provide a PRs for this? I'll be happy to add your contribution to the project.
Thanks!

**Comment by albertodall** [comment]
In this case, it seems it's not possible to pass the `IStatelessSession` as a constructor parameter, because of this:

https://github.com/aspnet/CORS/issues/105

Anyway, it's correct to not manage the `IStatelessSession` lifetime here. I'm going to push a fix.

**Comment by lcetinapta** [comment]
you can pas the stateless session as func<istatelesssession> .

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
