### ISSUE TITLE
MySql support

### ISSUE THREAD

**Issue by pigsi** [albertodall/IdentityServer4.NHibernate#13]
Hi ,
 I've tried to use MySql or Postgres but i'm having trouble with the reverved words (Key). the problem is that NHibernate produces SQL stament with the [<Field>] format, but brackets are not compatible with these databases. Can you provide a solution that also will work with other db's other that SQL Server and SQLite ?
Thank's

**Comment by MohamedElbasuony1** [comment]
any updates !? @pigsi  @albertodall

**Comment by albertodall** [comment]
Hello @pigsi Thanks for your feedback 
I think it's a matter of NHibernate configuration. I'll try to reproduce the issue and find a solution.

**Comment by pigsi** [comment]
Thank you Alberto, let me know if you have trouble to reproduce this issue.

**Comment by albertodall** [comment]
@pigsi @MohamedElbasuony1, I should have found the issue, and I'm going to push a fix ASAP.
Since MySQL and PostgreSQL are now first class citizens, I need to add these databases to the Integration Test suite.
