### ISSUE TITLE
SqlException: Incorrect syntax near the keyword 'Key'. After upgrading to 3.0.3

### ISSUE THREAD

**Issue by Hiller** [albertodall/IdentityServer4.NHibernate#15]
First of all thanks for your great work.

After upgrading from version 3.0.2 to 3.0.3 I'm getting an exception 
SqlException: Incorrect syntax near the keyword 'Key'. 
when opening opeindconfiguration or login page. 
I tried to add column autoquoting 
`SchemaMetadataUpdater.QuoteTableAndColumns(configuration, dialect);`
but it doesn't work.
[exception.txt](https://github.com/albertodall/IdentityServer4.NHibernate/files/7101020/exception.txt)
my configuration is 
`<hibernate-configuration xmlns="urn:nhibernate-configuration-2.2">
  <session-factory>
    <property name="connection.driver_class">NHibernate.Driver.Sql2008ClientDriver</property>
    <property name="connection.connection_string"></property>
    <property name="dialect">NHibernate.Dialect.MsSql2012Dialect,NHibernate</property>
    <property name="show_sql">true</property>
    <property name="command_timeout">120</property>
  </session-factory>
</hibernate-configuration>`

**Comment by albertodall** [comment]
Hi @Hiller 
happy to know that my work has been useful for you!
The script creator class already manages the column auto-quoting when it creates database schema scripts:
https://github.com/albertodall/IdentityServer4.NHibernate/blob/e7f019d50a1a29d0e79b858819df0e7dc04914c2/IdentityServer4.NHibernate.Storage/Database/Schema/ScriptCreator.cs#L46
Since I added the column auto-quoting to properly support PostgreSQL and MySql, I kindly ask you if you can create a brand-new database using the scripts from the library's latest version and run your application against it.
If it works, maybe it's a schema migration issue that I need to clearly address in the docs.
Meanwhile, I'll try to repro the issue ASAP.
Thank you!

**Comment by albertodall** [comment]
Hello @Hiller,
The issue should be related the the `dbo.ClientProperties` table, that has a `Key` field in it.
I tried to repro your case, and looking at the StackTrace you sent me, the issue should happen while calling the `ClientStore.FindClientByIdAsync()` method, where the generated query on your side doesn't have the `Key` field name surrounded by square brackets
```sql
properties3_.Key as key2_15_1_,
```
In the integration tests codebase, there's a (passing) test that should cover your case:
https://github.com/albertodall/IdentityServer4.NHibernate/blob/e7f019d50a1a29d0e79b858819df0e7dc04914c2/IdentityServer4.NHibernate.IntegrationTests/ConfigurationStore/ClientStoreFixture.cs#L382
Looking at the SQL statements generated while running the test, I noted that on my side, the `Key` field is surrounded by square brackets:
```sql
properties3_.[Key] as Key2_9_1_,
```
that prevents the error to happen. So, it seems that there are differences in the NHibernate generated SQL statements.
I suggest you to create a brand-new database using the latest version scripts and compare its schema with your actual one, to see if we can spot some differences.

What version of NHibernate are you using in your project?

**Comment by Hiller** [comment]
The main problem is here
https://github.com/albertodall/IdentityServer4.NHibernate/blob/e7f019d50a1a29d0e79b858819df0e7dc04914c2/IdentityServer4.NHibernate/IdentityServerBuilderNHibernateExtensions.cs#L117-L128
After adding StoreMappings and before calling BuildSessionFactory you should call  SchemaMetadataUpdater.QuoteTableAndColumns(configuration, dialect); 
otherwise 
`The NHibernate.ISessionFactory will be immutable, so changes made to the configuration after building the NHibernate.ISessionFactory will not affect it.
`
This means that Key field will never be quoted. In your test you're doing the right thing.
`SchemaMetadataUpdater.QuoteTableAndColumns(DbConfig, Dialect.GetDialect(DbConfig.Properties));
SessionFactory = DbConfig.BuildSessionFactory();`
exchange those lines and you'll got my error

**Comment by albertodall** [comment]
You're right!
I can fix it, but if you want, you could open a PR. 😉

**Comment by Hiller** [comment]
PR created

**Comment by albertodall** [comment]
@Hiller I merged your PR and I added you to the list of projects contributors.
Thanks for your feedback and for your support!
