### ISSUE TITLE
Automapper 8 - 9 version mismatch

### ISSUE THREAD

**Issue by chrisism** [albertodall/IdentityServer4.NHibernate#4]
With version 1.1.2 the nuspec sets the dependency to Automapper 8, but the storage project has a dependency on Automapper 9.
This results in:
An unhandled exception occurred while processing the request.
FileLoadException: Could not load file or assembly 'AutoMapper, Version=9.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
IdentityServer4.NHibernate.Extensions.ResourceStoreMappingExtensions.ToModel(ApiResource entity)

Match the versions up between nuspec and project to fix.

**Comment by albertodall** [comment]
Hello @chrisism, and thanks for reporting this issue.
I'm going to address it ASAP.

**Comment by chrisivo** [comment]
Hi folks, great work on this project. I think the nuspec issue has reoccured with the latest version - IdentityServer4.NHibernate.Storage, Version=3.0.4.0 requires AutoMapper, Version=10.1.1,  but instead the package nuspec file states:

`<dependency id="AutoMapper" version="9.0.0" />`

Much appreciated if you can sort this one.
