### ISSUE TITLE
Invalid DI configuration

### ISSUE THREAD

**Issue by lcetinapta** [albertodall/IdentityServer4.NHibernate#8]
Hi, the DI configuration is invalid...
You're adding  TokenCleanupService as singleton : 
`builder.Services.AddSingleton<TokenCleanupService>();`

That service requires NHibernate IStatelessSession that You're registering as scoped:
`builder.Services.AddScoped(provider =>
            {
                var factory = provider.GetService<ISessionFactory>();
                return factory.OpenStatelessSession();
            });
`

When the runtime tries to create an TokenCleanupService instance it throws an exception:
`InvalidOperationException: Cannot consume scoped service 'NHibernate.IStatelessSession' from singleton 'IdentityServer4.NHibernate.TokenCleanupService'.`

Eighter register TokenCleanupService as scoped or change it's constructor to require a factory for IStatelessSession.

**Comment by mtivan** [comment]
I second that. I took the first approach and it works. maybe we should just do the pull requests :-) i will try to do it today.

**Comment by mtivan** [comment]
I did the pull request. Somehow cannot connect to the issue.

**Comment by albertodall** [comment]
Hi @mtivan , thanks for your contribution.
I'll take a look to your PR ASAP.
